title = "Jenetics"
baseURL = "http://jenetics.io/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 13 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-33475513-2"
enableRobotsTXT = true

#[sitemap]
#  changefreq = "monthly"
#  priority = 0.5
#  filename = "sitemap.xml"

[params]
  favicon = "/favicon.ico"
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/jeneticsga"
  instagram = ""
  youtube = ""
  github = "https://github.com/jenetics/jenetics"
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"

